services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: ${CONTAINER_NAME}
    network_mode: bridge
    cpu_shares: 2048
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ${TRANSCODE_PATH}:/transcode
      - ${CONFIG_PATH}/${CONTAINER_NAME}:/config
      - ${MEDIA_PATH}/tv:/data/tvshows:ro
      - ${MEDIA_PATH}/movies:/data/movies:ro
      - ${MEDIA_PATH}/music:/data/music:ro
    devices: 
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096
    restart: unless-stopped
